spring:
  application:
    name: oauth1-resource
security:
  oauth2:
    client:
      client-id: resource
      client-secret: 123456
    resource:
      id: resource
      token-info-uri: http://localhost:8080/oauth/check_token #校验token的合法性

server:
  port: 8081
  servlet:
    context-path: /contents
