spring:
  application:
    name: oauth2-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
server:
  port: 8080


mybatis:
    type-aliases-package: com.zy.model
    mapper-locations: classpath:mapper/*.xml